add: Button, IconButton 컴포넌트 추가
thinoo-v2/upleat-ui pull request #11
Opened 2024-12-03 09:00 UTC by artofmouse

## 작업 주제

- Button, IconButton 컴포넌트 추가

## optional 작업 내용(어떤 부분을 리뷰어가 집중해서 봐야할까요?)

- 수정 및 보완해야 할 부분이 있다면 의견 부탁드립니다.

## optional ClickUp 링크

- ClickUp에서 관리중인 태스크 링크를 첨부합니다.

## optional 화면 스크린샷

![스크린샷 2024-12-04 오후 1 57 33](https://github.com/user-attachments/assets/2006f5f6-6f31-4900-83de-904391f755e7)

![스크린샷 2024-12-04 오후 1 55 44](https://github.com/user-attachments/assets/b659874e-ddcd-4f88-9701-9eaf72d9989c)

## optional 관련 Docs

## optional 추가 코멘트

- 추가적으로 리뷰어에게 전달하고 싶은 내용이 있다면 작성합니다.

## 체크리스트(PR 올리기 전 아래의 내용을 확인해주세요.)

- 추가 케이스가 있다면 코멘트 부탁드립니다.

## 리뷰 규칙

- P2: 웬만하면 반영해 주세요 (Comment)

2024-12-03 10:28 UTC, thinoo-v2 commented
@artofmouse 
좋습니다! 이것도 명시해주세요~

<img width="312" alt="image" src="https://github.com/user-attachments/assets/cbee8c41-fe80-493b-9e53-df53c700c25d">

2024-12-03 10:31 UTC, thinoo-v2 approved these changes
제가 의도한대로 --upleat- variable을 사용하셨네요. 
굿굿굿!!!!

2024-12-03 10:33 UTC, thinoo-v2 requested changes
typo에러입니다~
IconHamberger.tsx IconHamburger.tsx로 바꿔주세요~

2024-12-04 00:24 UTC, artofmouse commented
@thinoo-v2 
typo 에러 수정해서 푸시 했습니다.
IconHamberger.tsx -> IconHamburger.tsx 로 수정완료.

2024-12-04 11:01 UTC, thinoo-v2 approved these changes
👍

2024-12-04 11:01 UTC, merged